// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoxEzIO-6ktkMWYOO6JTGc50Av-Pedk94',
    appId: '1:1094123626171:web:45ae8dc24ec32eead7139e',
    messagingSenderId: '1094123626171',
    projectId: 'university-task',
    authDomain: 'university-task.firebaseapp.com',
    storageBucket: 'university-task.appspot.com',
    measurementId: 'G-PGTXMYFX76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCsBrxGwi-EgzMeMzxPHBcxR-xPGqnNSU',
    appId: '1:1094123626171:android:1fbe946fae637c8ed7139e',
    messagingSenderId: '1094123626171',
    projectId: 'university-task',
    storageBucket: 'university-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaC6ARhiINUbI5BvW0CtpLNWz903WGidk',
    appId: '1:1094123626171:ios:a22f15991b5b69f4d7139e',
    messagingSenderId: '1094123626171',
    projectId: 'university-task',
    storageBucket: 'university-task.appspot.com',
    iosBundleId: 'com.example.taskUniFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaC6ARhiINUbI5BvW0CtpLNWz903WGidk',
    appId: '1:1094123626171:ios:e0420e0e200851bcd7139e',
    messagingSenderId: '1094123626171',
    projectId: 'university-task',
    storageBucket: 'university-task.appspot.com',
    iosBundleId: 'com.example.taskUniFirebase.RunnerTests',
  );
}
